scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.99.1:8080' ]
  - job_name: node
    static_configs:
      - targets: [ '192.168.99.1:9100' ]
      - targets: [ '192.168.99.1:8080' ]
