server:
  host: localhost
  port: 2236
  address: 0.0.0.0
storage:
  location: upload
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
recipient:
  graphLen: 12000
  sigScale: 0.00001
  gestureSize: 2000
  packetSize: 528
  maxThreshold: 0.5
  minThreshold: 0.05
  waitingConnectionTimeout: 10000
  waitingReadTimeout: 5000

