version: '3.7'

services:
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./docker/config/prometheus.yml:/etc/prometheus/prometheus.yml
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#  node_exporter:
#    image: quay.io/prometheus/node-exporter:latest
#    container_name: node_exporter
#    command:
#      - '--path.rootfs=/host'
#    network_mode: host
#    pid: host
#    restart: unless-stopped
#    volumes:
#      - '/:/host:ro,rslave'
  emg_server:
    image: emg-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./upload:/app/upload