global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: emg-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]
  - job_name: node
    metrics_path: '/actuator'
    static_configs:
      - targets: [ 'localhost:9100' ]
