spring:
  config:
    location: classpath:/,file:./application.yaml
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
#  metrics:
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true
#  prometheus:
#    metrics:
#      export:
#        enabled: true